<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>LauncherSieuGunnyV1</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net40</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>Preview</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>logo remake1.ico</ApplicationIcon>
    <RootNamespace />
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageIcon>logo remake1.png</PackageIcon>
    <PackageIconUrl />
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="FontAwesome\**" />
    <Compile Remove="MetroFramework2\**" />
    <Compile Remove="Microsoft\**" />
    <Compile Remove="WinFormAnimation2\**" />
    <Compile Remove="WinFormAnimation\**" />
    <EmbeddedResource Remove="FontAwesome\**" />
    <EmbeddedResource Remove="MetroFramework2\**" />
    <EmbeddedResource Remove="Microsoft\**" />
    <EmbeddedResource Remove="WinFormAnimation2\**" />
    <EmbeddedResource Remove="WinFormAnimation\**" />
    <None Remove="FontAwesome\**" />
    <None Remove="MetroFramework2\**" />
    <None Remove="Microsoft\**" />
    <None Remove="WinFormAnimation2\**" />
    <None Remove="WinFormAnimation\**" />
    <None Include="..\..\Downloads\New folder (7)-20221208T115758Z-001\New folder (7)\logo remake1.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Remove="CircularProgressBar\CircularProgressBar.bmp" />
    <None Remove="LauncherGHU\cedrus.Bembemgunny.exe" />
    <None Remove="LauncherGHU\cedrus.cedrus.ghu" />
    <None Remove="LauncherGHU\cedrus.gunhoiuc.ghu" />
    <None Remove="LauncherGHU\cedrus.Gunhoiuc.exe" />
    <None Remove="fonts\fa-regular-400.ttf" />
    <None Remove="fonts\fa-solid-900.ttf" />
    <None Remove="fonts\fa-brands-400.ttf" />
    <None Remove="MaterialSkin\Resources.Roboto-Regular.ttf" />
    <None Remove="MaterialSkin\Resources.Roboto-Medium.ttf" />
    <EmbeddedResource Include="CircularProgressBar\CircularProgressBar.bmp" />
    <EmbeddedResource Include="LauncherGHU\cedrus.cedrus.ghu" />
    <EmbeddedResource Include="LauncherGHU\cedrus.gunhoiuc.ghu" />
    <EmbeddedResource Include="fonts\fa-regular-400.ttf" />
    <EmbeddedResource Include="fonts\fa-solid-900.ttf" />
    <EmbeddedResource Include="fonts\fa-brands-400.ttf" />
    <EmbeddedResource Include="MaterialSkin\Resources.Roboto-Regular.ttf" />
    <EmbeddedResource Include="MaterialSkin\Resources.Roboto-Medium.ttf" />
  </ItemGroup>
  <ItemGroup>
    <None Include="MetroFramework\MetroFramework.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="PresentationFramework" />
    <Reference Include="System.Xaml" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Core" />
    <Reference Include="System.Design" />
    <Reference Include="System.Data" />
    <Reference Include="WindowsBase" />
    <Reference Include="PresentationCore" />
    <Reference Include="Microsoft.VisualBasic" />
    <Reference Include="Microsoft.VisualBasic" />
    <Reference Include="System.Deployment" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Management" />
    <Reference Include="System.Web" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FontAwesome.Sharp" Version="5.15.3" />
    <PackageReference Include="VisualBasic.PowerPacks.Vs" Version="1.0.0" />
    <PackageReference Include="WinFormAnimation" Version="1.6.0.4" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>