<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="obj\Debug\.NETFramework,Version=v4.7.2.AssemblyAttributes.cs" />
    <Compile Include="obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.cs" />
    <Compile Include="obj\Debug\net5.0\tank.request2.AssemblyInfo.cs" />
    <Compile Include="obj\Debug\net5.0\tank.request2.RazorAssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="bin\Languages\Language-vn.txt" />
    <Content Include="obj\Debug\Tank.Request.csproj.FileListAbsolute.txt" />
    <Content Include="obj\project.assets.json" />
    <Content Include="obj\tank.request2.csproj.nuget.dgspec.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include=".vs\Tank.Request\config\applicationhost.config" />
    <None Include=".vs\Tank.Request\v16\.suo" />
    <None Include=".vs\Tank.Request\v17\.suo" />
    <None Include="bin\Ajax.dll" />
    <None Include="bin\Bussiness.dll" />
    <None Include="bin\Bussiness.pdb" />
    <None Include="bin\Game.Base.dll" />
    <None Include="bin\Game.Base.pdb" />
    <None Include="bin\log4net.dll" />
    <None Include="bin\Newtonsoft.Json.dll" />
    <None Include="bin\protobuf-net.Core.dll" />
    <None Include="bin\protobuf-net.dll" />
    <None Include="bin\Road.Flash.dll" />
    <None Include="bin\Road.Flash.pdb" />
    <None Include="bin\SqlDataProvider.dll" />
    <None Include="bin\SqlDataProvider.pdb" />
    <None Include="bin\System.Buffers.dll" />
    <None Include="bin\System.Collections.Immutable.dll" />
    <None Include="bin\System.Memory.dll" />
    <None Include="bin\System.Net.Http.Formatting.dll" />
    <None Include="bin\System.Numerics.Vectors.dll" />
    <None Include="bin\System.Runtime.CompilerServices.Unsafe.dll" />
    <None Include="bin\Tank.Request.dll" />
    <None Include="bin\Tank.Request.dll.config" />
    <None Include="bin\Tank.Request.pdb" />
    <None Include="bin\zlib.net.dll" />
    <None Include="obj\Debug\DesignTimeResolveAssemblyReferences.cache" />
    <None Include="obj\Debug\DesignTimeResolveAssemblyReferencesInput.cache" />
    <None Include="obj\Debug\net5.0\tank.request2.AssemblyInfoInputs.cache" />
    <None Include="obj\Debug\net5.0\tank.request2.assets.cache" />
    <None Include="obj\Debug\net5.0\tank.request2.csproj.AssemblyReference.cache" />
    <None Include="obj\Debug\net5.0\tank.request2.GeneratedMSBuildEditorConfig.editorconfig" />
    <None Include="obj\Debug\net5.0\tank.request2.RazorAssemblyInfo.cache" />
    <None Include="obj\Debug\Tank.Request.csproj.AssemblyReference.cache" />
    <None Include="obj\Debug\Tank.Request.csproj.CopyComplete" />
    <None Include="obj\Debug\Tank.Request.csproj.CoreCompileInputs.cache" />
    <None Include="obj\Debug\Tank.Request.dll" />
    <None Include="obj\Debug\Tank.Request.pdb" />
    <None Include="obj\Debug\TempPE\DbMember.designer.cs.dll" />
    <None Include="obj\project.nuget.cache" />
    <None Include="obj\tank.request2.csproj.nuget.g.props" />
    <None Include="obj\tank.request2.csproj.nuget.g.targets" />
    <None Include="Tank.Request.csproj" />
    <None Include="Tank.Request.csproj.user" />
    <None Include="Tank.Request.sln" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="bin\Debug\net5.0\ref\" />
    <Folder Include="obj\Debug\net5.0\ref\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Service References\CenterService\Reference.svcmap">
      <Generator>WCF Proxy Generator</Generator>
    </None>
  </ItemGroup>

</Project>
