namespace Game.Server.Packets
{
    public enum NoviceActiveType
    {
        Level_Atlama = 1,
        VIP_LEVEL = 2,
        SAVAS_GUCU = 3,
        Silah_Guclendirme = 4,
        Kiyafet_Guclendirme = 5,
        Sapka_Guclendirme = 6,
        DestekEkipmaniGuclendirme = 7,
        BIRLIK_SAVASI = 8,
        Ozgur_Savas = 9,
        Kesif_Tamamlama = 10,
        DISCORD_HOPARLORU = 11,
        Gunluk_Harcama = 12,
        Haftalik_Harcama = 13,
        TOHUM_EKME = 14,
        TOHUM_TOPLAMA = 15,
        Arkadasdan_Ekin_Calma = 16,
        PET_SAHIPLENME = 17,
        PET_SEVIYE = 18,
        KART_TAKMA = 19,
        ITEM_BIRLESTIRME = 20,
        ITEM_FUZYON = 21,
        ILK_EVLENME = 22,
        CIRAKLIK_ALMA = 23,
        USTA_OLMA = 24,
        LONCA_KATILMA = 25,
        MAC_KAZANMA_SERISI = 26,
        TOPLAM_HASAR = 27,
        ILK_BOSS_OLDURME = 28,
        EKIPMAN_SETI_TAMAMLAMA = 29,
        TOTEM_ACMA = 30,
        Ilk_Yukleme = 31,
        CIFTLIK_HASAT = 32,
        BUFF_KULLANIMI = 33,
        GUNLUK_GOREV_TAMAMLAMA = 34,
        ALTIN_TOPLAMA = 35
    }
}
